### ISSUE TITLE
Time.timeScale = 0の場合、シートが反応しない不具合

### ISSUE THREAD

**Issue by Hoshinari55** [Haruma-K/UnityDebugSheet#21]
初めまして。素晴らしいプロジェクトを共有していただきありがとうございます。
UnityDebugSheetを使用して、1つ不具合を発見しましたので報告させていただきます。

<hr>

### 不具合の概要
Time.timeScale = 0に設定されている場合、シートを操作しても反応せず、アニメーションが止まってしまう

<hr>

### 再現手順
1. CharacterViewerDemo.csに以下の記述を追加する。
2. PlayModeでAキーを押し、タイムスケールを0にする。
3. シートの各項目を操作してみる。
```
        private bool _isScaledTime = true;

        private void Update()  
        {  
            if (Input.GetKeyDown(KeyCode.A))  
            {  
                _isScaledTime = !_isScaledTime;  
                Time.timeScale = _isScaledTime ? 1 : 0;  
            }  
        }  
```

<hr>

### 期待される結果
シートが操作可能であり、アニメーションが正常に動作すること。

<hr>

### 実際の結果
シートを操作することができず、アニメーションが止まってしまう。

<hr>

### 環境情報
- Unity 2020.3.35 f1
- Windows 10 21H2

<hr>

この問題の修正をお願いできますでしょうか。よろしくお願いいたします。

**Comment by Haruma-K** [comment]
ご指摘ありがとうございます！

unscaledTimeを使う形に諸々修正いたします。
時間が取れる時に対応しますので、数日お待ちください。

**Comment by Hoshinari55** [comment]
確認ありがとうございます！
ご対応の程よろしくお願いいたします。

**Comment by Haruma-K** [comment]
Related PR: https://github.com/Haruma-K/UnityDebugSheet/pull/22

**Comment by Haruma-K** [comment]
@Hoshinari55 
修正し、1.5.2としてリリースいたしました。ありがとうございました！

https://github.com/Haruma-K/UnityDebugSheet/releases/tag/1.5.2

**Comment by Hoshinari55** [comment]
unscaledTimeで動作することを確認できました！
ご対応いただきありがとうございました。
