### ISSUE TITLE
🐛  Windowsネイティブビルドにてショートカットを使用してデバッグ画面が起動しない件について

### ISSUE THREAD

**Issue by KeigoTakamura** [Haruma-K/UnityDebugSheet#4]
初めまして。
Windowsビルドにて正しく動作してないと思われる挙動と実装を確認いたしましたのでissueを立てさせていただきます。

# 再現環境
- Unity2020 3.26f1
- Windows10 H21H2
- 使用Keyboard Majestouch MINILA-R Convertible
## 再現Project
-UnityDebugSheet Demoプロジェクト `Assets/Demo/00_DemoEntry/Scenes/DemoEntry.unity` のCharacterViewer にて事象の再現を確認しております。
- CommitID
```
commit afc6b38d704665875f94dc2a1f3242273a7ee86f (HEAD -> master, tag: 1.1.0, origin/master, origin/HEAD)
Author: Haruki Yano <haruki.y.11g@gmail.com>
Date:   Thu Oct 6 20:15:37 2022 +0900

    bump
```

# 確認した事象
UnityEditor（Windows10)ではcurl+shift+Dでデバッグ画面が立ち上がるがWindowsビルドだと特に何も立ち上がらない現象を確認しました。

![image](https://user-images.githubusercontent.com/40245723/195332441-9a685f3c-c376-4423-9752-5b91e26cc8e4.png)

# 推測される原因
`Assets\UnityDebugSheet\Runtime\Core\Scripts\KeyboardShortcut.cs` の72行目付近にあるプラットフォーム指定マクロの条件漏れかと思われます。

```
#if UNITY_EDITOR_WIN
            return InputAdapter.GetKey(KeyCode.LeftControl) || InputAdapter.GetKey(KeyCode.RightControl);
#else
            return InputAdapter.GetKey(KeyCode.LeftCommand) || InputAdapter.GetKey(KeyCode.RightCommand);
#endif
```

でEditor以外では`LeftCommand` が指定されている為、Macintoshのキーコードでしか認識しないのが原因と推測されます。
まだ動作検証を行っていませんがこのロジックでは恐らく一般的な105配列を使用することが多いLinux版Unityユーザーなども同様の現象を観測するものと推測します。

# 修正案
本来であればPRを出すべきなのですが諸事情ですぐPRを出せる環境にないのでこちらの方提案させて頂きます。
私のWindows環境では動作を確認済みです。
ただこのライブラリはモバイル端末のデバッグ前提に開発された感を私が勝手に感じているのでショートカット機能は
Editor専用機能ということあればこのFIXは却下していただいても構いません。

```diff
diff --git a/Assets/UnityDebugSheet/Runtime/Core/Scripts/KeyboardShortcut.cs b/Assets/UnityDebugSheet/Runtime/Core/Scripts/KeyboardShortcut.cs
index 6b27a17..e001060 100644
--- a/Assets/UnityDebugSheet/Runtime/Core/Scripts/KeyboardShortcut.cs
+++ b/Assets/UnityDebugSheet/Runtime/Core/Scripts/KeyboardShortcut.cs
@@ -69,7 +69,7 @@ namespace UnityDebugSheet.Runtime.Core.Scripts

         private bool GetControlKey()
         {
-#if UNITY_EDITOR_WIN
+#if UNITY_EDITOR_LINUX || UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN || UNITY_STANDALONE_LINUX
             return InputAdapter.GetKey(KeyCode.LeftControl) || InputAdapter.GetKey(KeyCode.RightControl);
 #else
             return InputAdapter.GetKey(KeyCode.LeftCommand) || InputAdapter.GetKey(KeyCode.RightCommand);
```

**Comment by Haruma-K** [comment]
@KeigoTakamura 
情報、原因の特定までありがとうございます！

おっしゃる通り、こちら実装漏れになります（普段使っているエディタ用のコードのまま使ってしまいました）。
こちら修正しますので少々お待ちください。

**Comment by Haruma-K** [comment]
@KeigoTakamura 
1.1.1としてリリースしました。

https://github.com/Haruma-K/UnityDebugSheet/releases/tag/1.1.1

改めまして情報ありがとうございました！助かりました。

**Comment by KeigoTakamura** [comment]
素早いご対応ありがとうございます！
